[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "oEmbedPy"
authors = [{name = "Kazuya Takei", email = "myself@attakei.net"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: Apache Software License"]
dynamic = ["version", "description"]

[project.optional-dependencies]
cli = ["Click>=8"]

[project.scripts]
"oEmbed.py" = "oembedpy.cli:main"

[project.urls]
Home = "https://attakei-lab.github.io/oEmbedPy"

[tool.flit.module]
name = "oembedpy"
